### ISSUE TITLE
Problems with latest JDA alpha

### ISSUE THREAD

**Issue by stijnb1234** [Kaktushose/jda-commands#76]
I get an error when upgrading to the latest (`15`) JDA alpha build. I'm using the latest commit of the `dev-jda5` branch.

```
java.lang.NoSuchMethodError: 'net.dv8tion.jda.api.entities.MessageChannel net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent.getChannel()'
	at com.github.kaktushose.jda.commands.dispatching.parser.impl.DefaultSlashCommandParser.parse(DefaultSlashCommandParser.java:47)
	at com.github.kaktushose.jda.commands.dispatching.parser.impl.DefaultSlashCommandParser.parse(DefaultSlashCommandParser.java:23)
	at com.github.kaktushose.jda.commands.dispatching.parser.Parser.parseInternal(Parser.java:19)
	at com.github.kaktushose.jda.commands.dispatching.parser.ParserSupervisor.onGenericEvent(ParserSupervisor.java:95)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:365)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:109)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:80)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by stijnb1234** [comment]
Problem caused by the Channel Unions. Needs a lot of refactor to support them, but yeah...

https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-alpha.14

**Comment by Kaktushose** [comment]
jda-commands does not support alpha 15.

**Comment by stijnb1234** [comment]
> 

I understand. Will it in the feature?

**Comment by Kaktushose** [comment]
With the next release, yes.

**Comment by stijnb1234** [comment]
Perfect! I see it's only caused by the tests, when I remove the tests it works fine for alpha 17.

**Comment by Kaktushose** [comment]
The unit tests implement JDA internal interfaces. So bumping the JDA version will likely break them
